### ISSUE TITLE
Doesn't see host schemas

### ISSUE THREAD

**Issue by Exalm** [flathub/ca.desrt.dconf-editor#3]
Since dconf-editor doesn't have access to host schemas, it (for the most part) only shows changed keys.

**Comment by nedrichards** [comment]
Yup, this is one of the reasons why we didn't put a lot of ongoing effort into this flatpak. It's certainly arguable if it should remain on flathub since it can't easily get access to the stuff that makes it very useful.

**Comment by TingPing** [comment]
It would be a simple patch for it to read the host schemas. The real part where `dconf-editor` be it in flatpak or host falls apart now is that with every app being in its own container it sees fewer and fewer schemas as time goes on.

**Comment by Exalm** [comment]
True. Maybe flatpak should allow apps exporting schemas in the future?

**Comment by TingPing** [comment]
The feature would exist only for `dconf-editor` which sounds like not remotely worth it.

**Comment by TingPing** [comment]
So in quick testing this almost works: `flatpak run --filesystem=host --env=GSETTINGS_SCHEMA_DIR=/var/run/host/usr/share/glib-2.0/schemas ca.desrt.dconf-editor`

It fails though because the dconf-editor schema among others may not actually exist on the host so it needs to support multiple directories in some form.
